### PR TITLE
fix(TimeCapsule): removed TimeCapsule collection 

### PR DESCRIPTION
**Pull request by chrismferguson**
This is the issue: https://github.com/dev-launchers/strapiv4/issues/127

### CODE REVIEW

**Comment by chungthuang** [comment]
The changes looks good. Just one little thing, can we change the commit to follow this format https://github.com/semantic-release/semantic-release#commit-message-format? This is a small change so we can use fix release type.

**Review by chungthuang — APPROVED** [review]

**Comment by becevka** [comment]
I noticed in other PRs in the repo the message is fix(authorname) but in the document it seems to be fix(domain-area) @chungthuang what approach we want to follow?

**Review by becevka — APPROVED** [review]
I think we need to rethink use of binary code in version control, like data.db. But I will table this discussion into Discord channel.

**Comment by chungthuang** [comment]
> I noticed in other PRs in the repo the message is fix(authorname) but in the document it seems to be fix(domain-area) @chungthuang what approach we want to follow?

I usually do `fix(author name)`.

**Pull request merged**
