### PR TITLE
feat(chungthuang): Migrate opportunity collection

### PR DESCRIPTION
**Pull request by chungthuang**
Migrate https://github.com/dev-launchers/strapi/tree/main/api/opportunities.
Resolves: #40

### CODE REVIEW

**Review by apglab — COMMENTED** [review]
Have the changes been tested?

**Comment by chungthuang** [comment]
@mfvil is testing it.

**Review by VictorDiniz89 — COMMENTED** [review]
Everything is confering with documentation of starpi v4

**Review by pyxld-kris — APPROVED** [review]
LGTM

**Review by pyxld-kris — APPROVED** [review]
LGTM

**Pull request merged**
